name: first workflow test
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - name: first run echo
        run: echo "first echo run!"
      - name: second run echo
        run: echo "second echo run successful!!!"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::881490103233:role/github-actions-role
          role-session-name: samplerolesession
          aws-region: ap-southeast-2
      # Upload a file to AWS s3
      - name: List s3 Buckets in Sydney Region
        run: |
          aws s3 ls
