name: first workflow test
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      AWS_ASSUME_ROLE: ${{ secrets.AWS_ROLE }}
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - name: first run echo
        run: echo "first echo run!"
      - name: second run echo
        run: echo "second echo run successful!!!"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
          role-session-name: samplerolesession
          aws-region: ap-southeast-2
      # Upload a file to AWS s3
      - name: List s3 Buckets in Sydney Region
        run: |
          aws s3 ls
      - name: Echo AWS ROLE Secrets
        run: echo "AWS Assume Role\:\ ${{ env.AWS_ASSUME_ROLE }} "        
